import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";

const googleSans = Google_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MiTask",
  description: "Generated by A1 MiTask",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.className} antialiased`}
        style={{ backgroundImage: "url('/pattern.webp')", backgroundRepeat: 'repeat', backgroundSize: '600px' }}
      >
        {children}
      </body>
    </html>
  );
}
